
###################################################
#
# Author CanXD
# Discord: canreolo
# Plugin Version: V2.0.3
# Yapım Tarihi: 16 kasım 2025
#
####################################################

# Multi Dil Özelliği Şuanki Desteklenen diller - en - tr -
language: "tr"
report-cooldown: 10
alerts-auto-enable-on-join: false #op'ler için geçerli

# Menülerin Slot Ayarlamaları. istediğiniz gibi ayarlayabilir değiştirebilirsiniz
# ancak 54 slot menüden taşmasın yoksa eklenti kendini kapatabilir.
gui:
  report-player:
    glass-slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52, 53]
    player-slots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43]
    next-page-slot: 51
    previous-page-slot: 47
  
  report-reasons:
    glass-slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36]
    reason-slots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34]
  
  reports:
    glass-slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52, 53]
    report-slots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43]
    next-page-slot: 51
    previous-page-slot: 47
  
  aacwatch:
    glass-slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52, 53]
    player-slots: [10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43]
    next-page-slot: 51
    previous-page-slot: 47

# Eklentinin Permissionları
###################################################
#  - aac.report
#  - aac.reports.view
#  - aac.reports.manage
#  - aac.watch
#  - aac.system.reload
#  - aac.admin
###################################################
